In [1]:
%pip install numpy pandas seaborn matplotlib scikit-learn joblib

Requirement already satisfied: numpy in .\.venv\Lib\site-packages (2.0.1)
Requirement already satisfied: pandas in .\.venv\Lib\site-packages (2.2.2)
Requirement already satisfied: seaborn in .\.venv\Lib\site-packages (0.13.2)
Requirement already satisfied: matplotlib in .\.venv\Lib\site-packages (3.11.2)
Requirement already satisfied: scikit-learn in .\.venv\Lib\site-packages (1.5.1)
Requirement already satisfied: joblib in .\.venv\Lib\site-packages (1.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (3.0.0)
Requirement already satisfied: pytz>=2020.1 in .\.venv\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: tzdata>=2022.7 in .\.venv\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: contourpy>=1.0.1 in .\.venv\Lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in .\.venv\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in .\.venv\Lib\site-packages (from matplotlib) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\.venv\Lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in .\.venv\Lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=9 in .\.venv\Lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=3 in .\.venv\Lib\site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: scipy>=1.6.0 in .\.venv\Lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in .\.venv\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in .\.venv\Lib\site-packages (from joblib) (3.1.2)
Requirement already satisfied: six>=1.6 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
import pandas as pd, sys
print(pd.__version__, sys.executable)

2.2.2 c:\Users\parth\OneDrive\Desktop\Netflix\ml-service\.venv\Scripts\python.exe

In [4]:
df = pd.read_csv("data/movies_metadata.csv")

In [5]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [6]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [8]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(13)

In [10]:
df=df.drop_duplicates().reset_index(drop=True)

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.isnull().sum()

adult                        0
belongs_to_collection    40959
budget                       0
genres                       0
homepage                 37673
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25045
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [13]:
df=df[['title','overview','genres','tagline','vote_average','popularity']]

In [14]:
df=df.dropna(subset=['title'])

In [15]:
df['overview']=df['overview'].fillna('')

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [18]:
import ast

df['genres'] = df['genres'].apply(
    lambda x: " ".join(i['name'] for i in ast.literal_eval(x))
)

In [19]:
df.iloc[0]['genres']

'Animation Comedy Family'

In [20]:
df['tagline']=df['tagline'].fillna('')

In [21]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [22]:
df['tags']=df['overview']+" "+df['genres']+" "+df['tagline']

In [23]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [24]:
df.iloc[0]['tags']

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation Comedy Family "

In [25]:
%pip uninstall -y nltk regex
%pip install --no-cache-dir nltk regex

Note: you may need to restart the kernel to use updated packages.

WARNING: Skipping nltk as it is not installed.
WARNING: Skipping regex as it is not installed.

Collecting nltk
  Downloading nltk-3.10.4-py3-none-any.whl.metadata (5.0 kB)
Collecting regex
  Downloading regex-2026.9.29-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting defusedxml (from nltk)
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: click in .\.venv\Lib\site-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in .\.venv\Lib\site-packages (from nltk) (1.6.0)
Collecting tqdm (from nltk)
  Downloading tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: cloudpickle>=3.0 in .\.venv\Lib\site-packages (from joblib->nltk) (3.1.2)
Requirement already satisfied: colorama in .\.venv\Lib\site-packages (from tqdm->nltk) (0.4.6)
Downloading nltk-3.10.4-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 13.4 MB/s  0:00:00
Downloading regex-2026.9.29-cp312-cp312-win_amd64.whl (280 kB)
Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Downloading tqdm-4.70.1-py3-none-any.whl (80 kB)
Installing collected packages: tqdm, regex, defusedxml, nltk

   ---------------------------------------- 0/4 [tqdm]
   -------------------- ------------------- 2/4 [defusedxml]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ---------------------------------------- 4/4 [nltk]

Successfully installed defusedxml-0.7.1 nltk-3.10.4 regex-2026.9.29 tqdm-4.70.1
Note: you may need to restart the kernel to use updated packages.

In [26]:
# %pip uninstall regex -y
# %pip install regex==2024.11.6 --no-cache-dir

In [27]:
# import sys
# !{sys.executable} -c "import regex; print(regex.__version__)"

In [28]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [29]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\parth\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\parth\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [30]:
stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()

In [31]:
def preprocess_text(text):
    text=str(text).lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    words=text.split()
    words = [word for word in words if word not in stop_words]
    words = [lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)

In [32]:
df['tags']=df['tags'].apply(preprocess_text)

In [33]:
df['tags']

0        led woody andys toy live happily room andys bi...
1        sibling judy peter discover enchanted board ga...
2        family wedding reignites ancient feud nextdoor...
3        cheated mistreated stepped woman holding breat...
4        george bank recovered daughter wedding receive...
                               ...
45448    rising falling man woman drama family rising f...
45449    artist struggle finish work storyline cult pla...
45450    one hit go wrong professional assassin end sui...
45451    small town live two brother one minister one h...
45452    year decriminalisation homosexuality uk direct...
Name: tags, Length: 45447, dtype: object

In [34]:
df.reset_index(drop=True)

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,led woody andys toy live happily room andys bi...
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,sibling judy peter discover enchanted board ga...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,family wedding reignites ancient feud nextdoor...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,cheated mistreated stepped woman holding breat...
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,george bank recovered daughter wedding receive...
...,...,...,...,...,...,...,...
45442,Subdue,Rising and falling between a man and woman.,Drama Family,Rising and falling between a man and woman,4.0,0.072051,rising falling man woman drama family rising f...
45443,Century of Birthing,An artist struggles to finish his work while a...,Drama,,9.0,0.178241,artist struggle finish work storyline cult pla...
45444,Betrayal,"When one of her hits goes wrong, a professiona...",Action Drama Thriller,A deadly game of wits.,3.8,0.903007,one hit go wrong professional assassin end sui...
45445,Satan Triumphant,"In a small town live two brothers, one a minis...",,,0.0,0.003503,small town live two brother one minister one h...
45446,Queerama,50 years after decriminalisation of homosexual...,,,0.0,0.163015,year decriminalisation homosexuality uk direct...

In [ ]:
indices=pd.Series(df.index,index=df['title']).drop_duplicates()

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [37]:
tfidf=TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [38]:
tfidf_matrix=tfidf.fit_transform(df['tags'])

In [50]:
print(tfidf.get_feature_names_out())

['aa' 'aamir' 'aamir khan' ... 'zu' 'zulu' 'zurich']

In [39]:
tfidf_matrix

<45447x50000 sparse matrix of type '<class 'numpy.float64'>'
	with 1548291 stored elements in Compressed Sparse Row format>

In [40]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [41]:
def recommend(title,n=10):
    if title not in indices:
        return ['Movie not Found']
    idx=indices[title]
    sim_score=cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
    similar_idx=sim_score.argsort()[::-1][1:n+1]
    return df['title'].iloc[similar_idx]

In [42]:
recommend("Toy Story")

2996                Toy Story 2
15344               Toy Story 3
24514                 Small Fry
28974           Superstar Goofy
17184                 Group Sex
6434     What's Up, Tiger Lily?
11396    For Your Consideration
1071      Rebel Without a Cause
1931                  Condorman
485                      Malice
Name: title, dtype: object

In [43]:
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))
pickle.dump(indices,open('indices.pkl','wb'))
df.to_pickle('df.pkl')

pickle.dump(tfidf,open('tfidf.pkl','wb'))